// Sáu cao thủ Thiếu Lâm — mỗi người một tuyệt kỹ với quỹ đạo & hiệu ứng riêng.
export const CHARACTERS = [
  {
    id: 'dragon',
    name: 'Đại Sư Huynh',
    skillName: 'Hàng Long Cước',
    desc: 'Một cước uy lực rung chuyển sân cỏ, bay thẳng như rồng xuyên mây.',
    color: 0xffcf4a,
    trail: 0xffd25c,
    special: 'shockwave',
  },
  {
    id: 'iron',
    name: 'Thiết Đầu Nhị Ca',
    skillName: 'Thiết Đầu Công',
    desc: 'Đường bóng cứng như thép, bay là là mặt đất, xuyên phá mọi cản phá.',
    color: 0xb9c4cf,
    trail: 0xdfe8ef,
    special: 'iron',
  },
  {
    id: 'taichi',
    name: 'Thái Cực Tam Ca',
    skillName: 'Thái Cực Toàn Phong',
    desc: 'Âm dương giao hòa, bóng lượn hình chữ S khiến thủ môn hoa mắt.',
    color: 0x7ee0c8,
    trail: 0x7ee0c8,
    special: 'taichi',
  },
  {
    id: 'fire',
    name: 'Liệt Hỏa Tứ Muội',
    skillName: 'Liệt Hỏa Phần Thiên Cước',
    desc: 'Bóng bốc cháy tự tăng tốc giữa không trung như thiên hỏa giáng thế.',
    color: 0xff6a4d,
    trail: 0xff6a2b,
    special: 'fire',
  },
  {
    id: 'phantom',
    name: 'Ảo Ảnh Ngũ Đệ',
    skillName: 'Thiên Ảnh Vạn Hình Cước',
    desc: 'Thân pháp ảo diệu, bóng tựa hồ dịch chuyển tức thời qua không gian.',
    color: 0xc48aff,
    trail: 0xc48aff,
    special: 'phantom',
  },
  {
    id: 'wind',
    name: 'Cuồng Phong Lục Ca',
    skillName: 'Cuồng Phong Toái Nhật Cước',
    desc: 'Xoáy lốc cuồng phong đẩy bóng lao đi với tốc độ kinh hồn.',
    color: 0x5ce0ff,
    trail: 0x5ce0ff,
    special: 'wind',
  },
];
